xclip/pbcopy : always copy explicitely in clipboard

diff --git a/default/bashrcc b/default/bashrcc
--- a/default/bashrcc
+++ b/default/bashrcc
@@ -71,8 +71,14 @@ ggprev() {
 
 OS=$(uname) # Linux , Darwin for mac
 if [ "$OS" == "Linux" ]; then
+  # -> go on chrome, select text (DO NOT ctrl-C)
+  # 'xclip -o -sel primary'
+  # -> will return the selected text :)
+
+  # 'xclip -o -sel clipboard'
+  # will return only what have been COPIED explicitely
   alias pbcopy='xclip -selection clipboard'
-  alias pbpaste='xclip -o'
+  alias pbpaste='xclip -o -sel clipboard'
   alias n=nautilus
   alias c=chrono_rb
 fi
@@ -279,7 +285,7 @@ getJSON() {
 # # undo the tweak to allow clean flipping to the next commit
 # git reset --hard
 # # return control
-# exit $status
+# return $status
 ##################################
 
 ## exclude file in git diff show
@@ -293,3 +299,38 @@ getJSON() {
 
 # compare two commit. And only the content :
 # v -d <(g show 11111111) <(g show 22222222)
+
+# parse what is in pbpaste
+# How to use :
+# go on gerrit
+# click on 'copy'
+# then open bash and type
+# cher
+# cher is for cherry-picking
+# function cher() {
+#   pbpaste
+#   echo
+#   echo
+#
+#   pbpaste | grep -q -P '^git fetch.+onemw-js.+ && git cherry-pick FETCH_HEAD$'
+#
+#   RESULT=$?
+#   if [ $RESULT -eq 0 ]; then
+#     echo -n '>>>>>>>>> '
+#     parse_git_branch
+#     echo
+#
+#     gerrit_part=$(pbpaste | sed 's/git fetch \(.\+\) && git cherry-pick FETCH_HEAD$/\1/')
+#     echo will fetch $gerrit_part
+#     echo
+#
+#     git fetch $gerrit_part
+#     echo
+#
+#     git checkout --detach
+#     git cherry-pick FETCH_HEAD
+#   else
+#     echo failed to match a gerrit cherry pick
+#     return 2
+#   fi
+# }
